<!-- Reviews.co.uk Rating Snippet -->
<?php
if ($block->isProductRatingSnippetWidgetEnabled() || $block->isCategoryRatingSnippetWidgetEnabled()) {
    $_data = $block->getSettings();
    $snippet = '
        ratingSnippet("ruk_rating_snippet", {
            store: "' . $block->escapeHtml($_data['store_id']) . '",
            mode: "default",
            color: "' . $_data["colour"] . '",
            linebreak: false,
            text: "Reviews",
            singularText: "Review",
            lang: "en",
            usePolaris: true,
            showEmptyStars: false,
        });
    ';
    $snippet = $block->getSecureHtmlRenderer()->renderTag('script', [], $snippet, false);
?>
    <script src="https://<?php /* @escapeNotVerified */ print $_data['api_url']; ?>/rating-snippet/dist.js"></script>
    <link rel="stylesheet" href="https://<?php /* @escapeNotVerified */ print $_data['api_url']; ?>/rating-snippet/dist.css" />
    <?= $snippet ?>
<?php
}
