<?php
# add copyright block.
# Add definition of Block.
# Use escaper instead of $block for escaping
if ($block->isProductRatingSnippetWidgetEnabled()):
    $_data = $block->getSettings();
    $_skus = $block->getProductSkus();
?>
    <div class="ruk_rating_snippet" data-sku="<?php print $block->escapeHtml((!empty($_skus) ? implode(';', $_skus) : '')) ?>"></div>
<?php endif; # never ending php?? ?>
