<?php
if ($block->isProductWidgetEnabled() && $block->isTabMode()){
    if ($block->isIframeWidget()) {
        $_data = $block->getSettings();
        $_skus = $block->getProductSkus();
        ?>
        <script src="https://<?php /* @escapeNotVerified */ print $_data['api_url']; ?>/product/dist.js"></script>
        <div id="widget"></div>
        <script type="text/javascript">
            productWidget("widget", {
                store: '<?php print $block->escapeHtml($_data['store_id']); ?>',
                sku: '<?php print $block->escapeHtml(implode(';', $_skus)); ?>', // Multiple SKU"s Seperated by Semi-Colons
                primaryClr: "<?php /* @noEscape */ print $_data['colour']; ?>",
                neutralClr: "#EBEBEB",
                buttonClr: "#EEE",
                textClr: "#333",
                tabClr: "#eee",
                questions: true,
                showTabs: true,
                ratingStars: false,
                showAvatars: true,
                translateAverage: '<?php /* @escapeNotVerified */ print __("Average");?>',
                translateReviews: '<?php /* @escapeNotVerified */ print __("Reviews");?>',
                translateNoReviews: '<?php /* @escapeNotVerified */ print __("No Reviews");?>',
                translateMoreRatings: '<?php /* @escapeNotVerified */ print __("More Ratings");?>',
                translateNoComments: '<?php /* @escapeNotVerified */ print __("This review has no comments");?>',
                translateReplyFrom: '<?php /* @escapeNotVerified */ print __("Reply from");?>',
                translatePosted: '<?php /* @escapeNotVerified */ print __("Posted");?>',
                translateWriteReview: '<?php /* @escapeNotVerified */ print __("Write a Review");?>',
                translateShow: '<?php /* @escapeNotVerified */ print __("Show");?>',
                translateDetails: '<?php /* @escapeNotVerified */ print __("Details");?>'
            });
        </script>
        <?php
    } else {
        print $block->getStaticWidget();
    }
}
?>
